---
title: "country's income by temperature"
output: pdf_document
---

```{r, echo=FALSE, include=FALSE}
library(tidyverse)
library(knitr)
opts_chunk$set(warning = FALSE, message = FALSE)
```

```{r}
world_gdp <- read_csv('API_NY.GDP.PCAP.CD_DS2_en_csv_v2_4019678.csv')
```

```{r}
world_gdp <- world_gdp %>%
  rename(
    gdp = `2019`,
    country = `...1`
    ) %>% 
  select(
    country,
    gdp
    ) %>% 
  na.omit(world_gdp)

temperature <- read_csv('table-1.csv')
temperature <- temperature %>% 
  rename(
    country = Country,
    temp = `Average yearly temperature (1961–1990 Celsius)`
  )

```

```{r}
# left merge
temperature_gdp <- merge(x = world_gdp, y = temperature, by = "country")
```

```{r}
temperature_income$temp <- as.numeric(temperature_income$temp)
```

```{r}
temperature_gdp %>% ggplot(aes(x = temp, y = gdp)) +
  geom_point(alpha = 0.5) + 
  geom_smooth(method = 'lm', se = FALSE) +
  theme_classic()
```

```{r}
model1 <- lm(gdp ~ temp, data = temperature_gdp)
summary(model1)$coefficients
cor(x = temperature_gdp$temp, y = temperature_gdp$gdp)
summary(model1)$r.squared
```