---
title: "The Correlation between Temperature and GDP per capita"
author: "Kunzhi (Alex) Yu"
date: "May 31, 2022"
output: pdf_document
---

## Introduction


```{r setup, echo=FALSE, include=FALSE}
library(tidyverse)
library(knitr)
opts_chunk$set(include = FALSE)
```

```{r}
# load data sets for states analysis
setwd('C:/Users/yukun/Personal/Projects/stats projects/temperature_gdp')
state_gdp <- read_csv('./data/bea_download.csv')
state_temps <- read_csv('./data/statetemps.csv')
state_pop <- read_csv('./data/nst-est2019-alldata.csv')
```

```{r}
# tidy data to only inc lude variables that will be used. Rename columns.
state_gdp <- state_gdp %>% 
  rename(
    State = GeoName,
    gdp = `2019`
  ) %>% 
  select(
    State,
    gdp
  )
  
state_pop <- state_pop %>% 
  rename(
    State = NAME,
    pop = POPESTIMATE2019
    ) %>% 
  select(
    State,
    pop
    )
```

```{r}
# left merge.
state_gdp_per_cap <- merge(x = state_gdp, y = state_pop, by = "State")
```

```{r}
# change gdp into gdp instead of gdp millions of dollars and calculate gdp per cap
state_gdp_per_cap <- state_gdp_per_cap %>%
  mutate(gdp = gdp * 1000000,
         gdp_per_cap = gdp / pop)
```

```{r}
# left merge.
state_temps_gdppc <- merge(x = state_gdp_per_cap, y = state_temps, by = "State")
```

```{r}
# tidy data to only include variables that will be used. Rename columns.
state_temps_gdppc <- state_temps_gdppc %>%
  rename(
    state = State,
    temp = `Avg C`
    ) %>% 
  select(
    state,
    gdp_per_cap,
    temp
  )
```

```{r, include = TRUE, echo = FALSE, message = FALSE}
# plot temperature in C versus GDP per capita
state_temps_gdppc %>%
  ggplot(aes(x = temp, y = gdp_per_cap)) +
  geom_point(alpha = 0.5) + 
  geom_smooth(method = 'lm', se = FALSE, formula = y~x) +
  labs(
    x = "Temperature / Degrees Celsius",
    y = "GDP per Capita / USD"
  ) +
  ggtitle("GDP per Capita Versus Temperature in Each U.S. State") +
  theme_minimal() +
  theme(plot.title = element_text(hjust = 0.5))
```

```{r}
# print regression details
states_lm <- lm(gdp_per_cap ~ temp, data = state_temps_gdppc)
cor(x = state_temps_gdppc$temp, y = state_temps_gdppc$gdp_per_cap)
summary(states_lm)
```

```{r}
# read data for world
world_gdp <- read_csv('./data/API_NY.GDP.PCAP.CD_DS2_en_csv_v2_4019678.csv')
world_temp <- read_csv('./data/table-1.csv')
```

```{r}
# wrangle data. rename variables and select variables that will be used.
world_gdp <- world_gdp %>%
  rename(
    gdppc = `2019`,
    country = `...1`
    ) %>% 
  select(
    country,
    gdppc
    ) %>% 
  na.omit(world_gdp)

world_temp <- world_temp %>% 
  rename(
    country = Country,
    temp = `Average yearly temperature (1961–1990 Celsius)`
  )
```

```{r}
# left merge
global_temps_gdppc <- merge(x = world_gdp, y = world_temp, by = "country")
```

```{r, include = TRUE, echo = FALSE, message = FALSE}
# plot temperature versus GDP per capita
global_temps_gdppc %>% 
  ggplot(aes(x = temp, y = gdppc)) +
  geom_point(alpha = 0.5) + 
  geom_smooth(method = 'lm', se = FALSE, formula = y ~ x) + 
  labs(
    x = "Temperature / Degrees Celsius",
    y = "GDP per Capita / USD"
  ) +
  ggtitle("GDP per Capita Versus Temperature in Each Country") +
  theme_minimal() +
  theme(plot.title = element_text(hjust = 0.5))
```

```{r}
# regression details
global_lm <- lm(gdppc ~ temp, data = global_temps_gdppc)
cor(x = global_temps_gdppc$temp, y = global_temps_gdppc$gdp)
summary(global_lm)
```

## Bibliography

https://wid.world/data/
https://en.wikipedia.org/wiki/List_of_countries_by_average_yearly_temperature
https://www.currentresults.com/Weather/US/average-annual-state-temperatures.php
https://apps.bea.gov/iTable/iTable.cfm?reqid=70&step=1&acrdn=2