---
title: "income_temperature"
output: pdf_document
---

```{r, echo=FALSE, include=FALSE}
library(tidyverse)
library(knitr)
opts_chunk$set(warning = FALSE, message = FALSE)
```

```{r}
# load data sets
income <- read_csv('IRSIncomeByZipCode.csv')
state_codes <- read_csv('statenamecode.csv')
state_temps <- read_csv('statetemps.csv')
```

```{r}
# tidy data to only include variables that will be used
income <- income %>% select(index,
                            ZIPCODE,
                            STATE,
                            `Adjusted gross income (AGI)`)

# rename some columns in <income>
income <- income %>%
  rename(
    zip = ZIPCODE,
    state_code = STATE,
    agi = `Adjusted gross income (AGI)`
  )

# create new variable that contains quartiles
income <- income %>% 
  mutate(percentile = case_when(agi <= 33003 ~ "25%",
                                agi > 33003 & agi <= 67463 ~ "50%",
                                agi > 67463 & agi <= 122500 ~ "75%",
                                agi > 122500 ~ "0%"))
```

```{r}
# left merge
state_temps <- merge(x = state_temps, y = state_codes, by = "State")
```

```{r}
# further wrangle <state_temps>
state_temps <- state_temps %>% 
  select(State,
         `Avg C`,
         Code) %>% 
  rename(
    state_name = State,
    temp = `Avg C`,
    state_code = Code
  )
```

```{r}
state_temps_income <- merge(x = income, y = state_temps, by = "state_code")
```

```{r}
state_temps_income %>%
  ggplot(aes(x = temp, y = agi)) +
  geom_point(alpha = 0.5) + 
  geom_smooth(method = 'lm', se = FALSE) +
  theme_minimal()
```

```{r}
model1 <- lm(agi ~ temp, data = state_temps_income)
summary(model1)$coefficients
cor(x = state_temps_income$temp, y = state_temps_income$agi)
summary(model1)$r.squared
```

```{r}
lower <- state_temps_income %>% filter(agi < 1600000)
model1 <- lm(agi ~ temp, data = lower)
summary(model1)$coefficients
cor(x = lower$temp, y = lower$agi)
summary(model1)$r.squared
```

```{r}
state_temps_income %>%
  filter(agi < 1600000) %>% 
  ggplot(aes(x = temp, y = agi)) +
  geom_point(alpha = 0.5) + 
  geom_smooth(method = 'lm', se = FALSE) +
  theme_minimal()
```


## Bibliography

https://wid.world/data/
https://en.wikipedia.org/wiki/List_of_countries_by_average_yearly_temperature
https://dqydj.com/average-median-top-household-income-percentiles/
https://www.kaggle.com/datasets/satoshidatamoto/irs-income-by-zip-code-a-deeper-looke?select=IRSIncomeByZipCode.csv
https://worldpopulationreview.com/states/state-abbreviations
https://www.currentresults.com/Weather/US/average-annual-state-temperatures.php